### ISSUE TITLE
Unhandled Runtime Error TypeError: Cannot read properties of null (reading 'readyState')

### ISSUE THREAD

**Issue by bovealexandre** [Ju99ernaut/grapesjs-tailwind#2]
Hi I'm using next.JS and I have this error whenever I use your other plugin (project manager) I had an error with project manager that I finally fixed but Tailwind is not working now

```
Unhandled Runtime Error
TypeError: Cannot read properties of null (reading 'readyState')

Call Stack
eval
node_modules\grapesjs-tailwind\dist\grapesjs-tailwind.min.js (2:324087)
```

**Comment by Ju99ernaut** [comment]
I'm not too sure but it's likely the canvas isn't loading properly

**Comment by bovealexandre** [comment]
whenever I remove the project manager it works well so I'm doing my own page manager and now it works but whenever I change page with the select function it removes tailwind so I'm trying to find a solution to take the whole head store it in a variable and put it in the new render

**Comment by bovealexandre** [comment]
ok now I've tried everything to make this plugin work with every way possible to make a Page Manager and i can't make it rerender once I change page

**Comment by bovealexandre** [comment]
@Ju99ernaut please can you help me to keep tailwind after changing page

**Comment by Ju99ernaut** [comment]
I'll look into it, can you provide more details of your setup and how to reproduce this issue

**Comment by artf** [comment]
Hi @Ju99ernaut in order to support multiple pages/frames with external resources in your plugin I'd suggest you subscribing to the frame's `loaded` event (similar to [SwitchVisibility command](https://github.com/artf/grapesjs/blob/master/src/commands/view/SwitchVisibility.js))

**Comment by bovealexandre** [comment]
here is my code if you want to watch @Ju99ernaut it's still a wip

https://github.com/bovealexandre/my-boilerplate/blob/main/src/pages/admin/editor.js

**Comment by Ju99ernaut** [comment]
Thanks @artf, will update the plugin
