### ISSUE TITLE
Get Tailwind CSS

### ISSUE THREAD

**Issue by beyond-these-walls** [Ju99ernaut/grapesjs-tailwind#6]
Finding the project really interesting and useful. Thanks.

Am using the command 'editor.runCommand('get-tailwindCss')' to get the tailwind CSS used in the editor.   

As the docs says, this outputs to the console, but can't find a way of getting the CSS as a variable I can save to a database.

**Comment by beyond-these-walls** [comment]
After looking into the code, settled on the following:

const doc = editor.Canvas.getDocument();

doc.head.querySelectorAll('style').forEach(el => {
    el.innerText.includes('tailwind');
    twcss = el.innerText;
});

document.getElementById("styles").value = twcss;

**Comment by congthang1** [comment]
Use this to get css
editor.runCommand('get-tailwindCss', { callback: async (twcss)=> { console.log(twcss } })
